-- Oracle 原始视图定义
-- Owner: HIGHWAY_STORAGE
CREATE OR REPLACE VIEW V_SERVERPARTSHOP_COMBINE AS
SELECT
	SERVERPART_ID,SERVERPART_NAME,SERVERPART_INDEX,SERVERPART_CODE,
	MIN(SERVERPARTSHOP_ID) AS SERVERPARTSHOP_ID,WM_CONCAT(SHOPNAME) AS SHOPNAME,
	BUSINESS_TYPE,SHOPTRADE,ISVALID,BUSINESS_UNIT,SHOPSHORTNAME,REGISTERCOMPACT_NAME,
	BUSINESS_TRADENAME,BRAND_NAME,MIN(SERVERPARTSHOP_INDEX) AS SERVERPARTSHOP_INDEX,
	MIN(BUSINESS_STATE) AS BUSINESS_STATE,MAX(BUSINESS_ENDDATE) AS BUSINESS_ENDDATE,
	PROVINCE_CODE,FIELDENUM_ID,SERVERPART_TYPE,REGIONTYPE_ID,SPREGIONTYPE_ID,SPREGIONTYPE_NAME,
	SPREGIONTYPE_INDEX,SERVERPART_ADDRESS,EXPRESSWAY_NAME,SERVERPART_X,SERVERPART_Y,
	WM_CONCAT(SERVERPARTSHOP_ID) AS SERVERPARTSHOP_IDS,MAX(TRANSFER_TYPE) AS TRANSFER_TYPE,
	WM_CONCAT(SHOPCODE) AS SHOPCODE,WM_CONCAT(SHOPREGION) AS SHOPREGION 
FROM
(
	SELECT 
		A.SERVERPART_ID,A.SERVERPART_NAME,A.SERVERPART_ADDRESS,A.SERVERPART_INDEX,
		A.EXPRESSWAY_NAME,A.SERVERPART_X,A.SERVERPART_Y,A.PROVINCE_CODE,
		A.SERVERPART_CODE,A.FIELDENUM_ID,A.SERVERPART_TYPE,A.REGIONTYPE_ID,
		A.SPREGIONTYPE_ID,A.SPREGIONTYPE_NAME,A.SPREGIONTYPE_INDEX,B.BUSINESS_TYPE,
		B.SHOPTRADE,B.ISVALID,B.SELLER_NAME AS BUSINESS_UNIT,B.SHOPSHORTNAME,B.REGISTERCOMPACT_NAME,
		B.BUSINESS_TRADENAME,B.BRAND_NAME,B.SERVERPARTSHOP_INDEX,B.SHOPREGION,B.SHOPCODE,
		B.SERVERPARTSHOP_ID,B.SHOPNAME,B.BUSINESS_STATE,B.BUSINESS_ENDDATE,B.TRANSFER_TYPE
	FROM
		HIGHWAY_STORAGE.T_SERVERPART A,
		HIGHWAY_STORAGE.T_SERVERPARTSHOP B
	WHERE
		A.SERVERPART_ID = B.SERVERPART_ID AND NVL(B.STATISTICS_TYPE,'0') NOT LIKE '%4010%' 
	ORDER BY
		A.SERVERPART_ID,B.SHOPREGION,B.SERVERPARTSHOP_ID 
)
GROUP BY 
	SERVERPART_ID,SERVERPART_NAME,SERVERPART_ADDRESS,SERVERPART_INDEX,EXPRESSWAY_NAME,
	SERVERPART_X,SERVERPART_Y,PROVINCE_CODE,SERVERPART_CODE,FIELDENUM_ID,SERVERPART_TYPE,
	REGIONTYPE_ID,SPREGIONTYPE_ID,SPREGIONTYPE_NAME,SPREGIONTYPE_INDEX,BUSINESS_TYPE,
	SHOPTRADE,ISVALID,BUSINESS_UNIT,SHOPSHORTNAME,REGISTERCOMPACT_NAME,BUSINESS_TRADENAME,BRAND_NAME 
